<a href="https://colab.research.google.com/github/LauraRS1/Listao_UFRGS_2022/blob/main/List%C3%A3o_UFRGS_PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Buscando os meus possíveis colegas no Listão :)

##### O listão online da UFRGS é uma série de listas em ordem alfabética. Irei importar para o Notebook e descobrir meus possíveis colegas de faculdade!  

##### Link de acesso dos dados: https://vestibular.ufrgs.br/cv2022/listao/

###Importando as bibliotecas

In [ ]:
import pandas as pd

### Pegando a lista de selecionados com o Pandas

In [ ]:
letras = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'r', 's', 't', 'u', 'v', 'w', 'y', 'z']  # Não há candidatos nas letras "q" e "x".

In [ ]:
listao = []

for letra in letras:
  listao.append((pd.read_html('https://vestibular.ufrgs.br/cv2022/listao/arquivo_'+letra+'.html')))

In [ ]:
# Visualizando...

listao[0][0].head()

,Inscrição,Nome,Vaga obtida,Semestre,Curso,Classificação
0,012590-3,Abyner da Silva Vargas,AC,2,Engenharia Elétrica,34°
1,010853-7,Acácia Rufatto,AC,1,Letras - Licenciatura,8°
2,008034-9,Adriana Cecchin Fajreldines,AC,2,Engenharia Hídrica,2°
3,017920-5,Adriana de Freitas Rodrigues,L4,1,Filosofia - Bacharelado Diurno,25°
4,016305-8,Adriane Inês Backes Sehn,AC,1,Geografia - Diurno,2°

### Concatenando as listas de DataFrames em um só.

In [ ]:
novo_listao = pd.concat([listao[0][0]])

for num in range(1, 24):
  novo_listao = novo_listao.append(pd.concat([listao[num][0]]))

In [ ]:
novo_listao.sample(5)

,Inscrição,Nome,Vaga obtida,Semestre,Curso,Classificação
25,009778-0,Danielly Borges Martins,L1,1,Fisioterapia,47°
90,019776-9,Bruna Strehl de Mello,AC,1,Ciências Jurídicas e Sociais - Direito - Diurno,25°
127,016188-8,Gabrielly Rodrigues Mendonça,L3,1,Biotecnologia,53°
84,009232-0,João Pedro Scheffer Lumertz,AC,1,Administração - Diurno,15°
113,000956-3,Cintia Liane Braucks,AC,1,Pedagogia,23°

# Pegando os aprovados em Ciência da Computação

In [ ]:
# É possível ver qualquer outro curso apenas trocando o nome da variável curso.

curso = ['Ciência da Computação']
selecao = novo_listao['Curso'].isin(curso)
dados = novo_listao[selecao].reset_index()
del dados['index']

In [ ]:
dados.head(5)

,Inscrição,Nome,Vaga obtida,Semestre,Curso,Classificação
0,000284-4,Afonso Hafner de Britto,AC,1,Ciência da Computação,16°
1,003987-0,Alice Farias Gomes,L2,2,Ciência da Computação,274°
2,010155-9,Andressa Della Torre Salgado,L1,2,Ciência da Computação,228°
3,007385-7,Anísio Neto Meneses Lorentz,AC,2,Ciência da Computação,31°
4,014936-5,Artur Coletti Valente,L3,2,Ciência da Computação,44°

###Fazendo algumas análises

In [ ]:
# Quem vai entrar no primeiro semestre?

dados.query('Semestre == 1')

,Inscrição,Nome,Vaga obtida,Semestre,Curso,Classificação
0,000284-4,Afonso Hafner de Britto,AC,1,Ciência da Computação,16°
5,011751-0,Beatriz Aline Arend,L1,1,Ciência da Computação,155°
6,007728-3,Beatriz Forneck Soviero,AC,1,Ciência da Computação,2°
7,007276-1,Bruno Fialho Zawacki,AC,1,Ciência da Computação,21°
8,011109-0,Bruno Martins Alexandre,L13,1,Ciência da Computação,220°
10,008704-1,Diego Hommerding Amorim,AC,1,Ciência da Computação,9°
11,000898-2,Eduarda da Silva Alves,L4,1,Ciência da Computação,224°
12,013127-0,Eduarda Tessari Pereira,AC,1,Ciência da Computação,6°
13,004595-0,Eduardo Godois Saldanha,L1,1,Ciência da Computação,210°
14,017922-1,Emilson Livramento Silva,L4,1,Ciência da Computação,185°
17,009427-7,Fernando Kaspary Fink,AC,1,Ciência da Computação,1°
19,013385-0,Gabriel Arusiewicz Berta,L1,1,Ciência da Computação,194°
20,002340-0,Gabriel Carvalho Ávila,AC,1,Ciência da Computação,5°
21,009835-3,Gabriel Carvalho Tavares,AC,1,Ciência da Computação,23°
22,018546-9,Gabriel dos Reis Vargas,L4,1,Ciência da Computação,244°
23,005274-4,Gabriel Fernando Giaretta,AC,1,Ciência da Computação,25°
24,013662-0,Gabriel Kenji Yatsuda Ikuta,AC,1,Ciência da Computação,15°
25,003968-3,Gabriel Zurawski de Souza,L2,1,Ciência da Computação,143°
26,004947-6,Guilherme Ismael Flach,AC,1,Ciência da Computação,7°
27,018514-0,Guilherme Poletti da Costa,L1,1,Ciência da Computação,95°
28,010998-3,Gustavo Bender,AC,1,Ciência da Computação,22°
30,006747-4,Gustavo Zen Pretto,AC,1,Ciência da Computação,17°
31,020177-4,Henrique Soares Ribeiro Sant'Anna de Oliveira,AC,1,Ciência da Computação,4°
35,019887-0,João Pedro Giordani de Souza,L14,1,Ciência da Computação,137°
36,009420-0,João Pedro Klippel Brusch,L13,1,Ciência da Computação,104°
37,008030-6,João Vitor Vogel,L1,1,Ciência da Computação,217°
38,011419-7,Jorge Antônio Noll dos Santos,L1,1,Ciência da Computação,206°
39,003368-5,Julianne Emanuelle Martins Carrazzoni,L2,1,Ciência da Computação,258°
40,012164-9,Kamille Konarzewski Pimentel,L1,1,Ciência da Computação,184°
41,007214-1,Laís Fernanda Canabarro Araujo,L3,1,Ciência da Computação,40°
42,009299-1,Laura Reis da Silveira,L4,1,Ciência da Computação,78°
43,012921-6,Leonardo Gonzatti Heisler,AC,1,Ciência da Computação,14°
44,008365-8,Leonardo Silva Faria,AC,1,Ciência da Computação,18°
45,019778-5,Luan Figueredo Dias,L13,1,Ciência da Computação,179°
47,015798-8,Lucas Campos Machado,AC,1,Ciência da Computação,24°
48,018226-5,Maicon Figueiró da Silva,L2,1,Ciência da Computação,266°
49,008828-5,Marcelo Gross Borges,AC,1,Ciência da Computação,13°
51,002723-5,Marcos da Silva Bagatini,L1,1,Ciência da Computação,148°
52,002139-3,Maria Eduarda Santos Oliveira,L1,1,Ciência da Computação,215°
53,001309-9,Mateus da Luz Matos Cezar,AC,1,Ciência da Computação,8°
54,001781-7,Miguel Lemmertz Schwarzbold,AC,1,Ciência da Computação,3°
55,019806-4,Nathan Hoffmann Passuello,AC,1,Ciência da Computação,12°
56,006242-1,Pedro Henrique Gomes Lourenço,L4,1,Ciência da Computação,253°
59,012311-0,Raquel da Silva Ramos,AC,1,Ciência da Computação,27°
60,006748-2,Roger Nathan Gonçalves Schmidt,L3,1,Ciência da Computação,37°
61,009128-6,Samuel Sodré da Rosa,L1,1,Ciência da Computação,208°
62,012813-9,Sandro Rudiero Saibro Viégas,AC,1,Ciência da Computação,20°
63,008316-0,Tális Breda,L1,1,Ciência da Computação,55°
64,007326-1,Thiago Frazzon Arend,AC,1,Ciência da Computação,26°
65,012049-9,Thomas Schneider Wiederkehr,L3,1,Ciência da Computação,38°
66,012197-5,Tiago Vieira Dillenburg,AC,1,Ciência da Computação,19°
68,004610-8,Vinícius Daniel Spadotto,AC,1,Ciência da Computação,10°
69,016961-7,Walter Frank,AC,1,Ciência da Computação,11°

In [ ]:
# Quem vai entrar no Segundo Semestre?

dados.query('Semestre == 2')

,Inscrição,Nome,Vaga obtida,Semestre,Curso,Classificação
1,003987-0,Alice Farias Gomes,L2,2,Ciência da Computação,274°
2,010155-9,Andressa Della Torre Salgado,L1,2,Ciência da Computação,228°
3,007385-7,Anísio Neto Meneses Lorentz,AC,2,Ciência da Computação,31°
4,014936-5,Artur Coletti Valente,L3,2,Ciência da Computação,44°
9,020160-0,Cristopher dos Santos Filho,AC,2,Ciência da Computação,28°
15,011023-0,Felipe Avencourt Soares,L13,2,Ciência da Computação,255°
16,014265-4,Felipe Thaddeu Gassen,AC,2,Ciência da Computação,35°
18,004248-0,Gabriel Alves Barbosa,AC,2,Ciência da Computação,33°
29,005805-0,Gustavo da Encarnação Rodrigues,L4,2,Ciência da Computação,259°
32,019600-2,Isasc Ventura de Oliveira,L4,2,Ciência da Computação,261°
33,007272-9,João Gabriel Eberhardt Pereira,AC,2,Ciência da Computação,34°
34,012905-4,João Gabriel Rau Wendt,AC,2,Ciência da Computação,30°
46,001395-1,Luca Mello Piccoli,AC,2,Ciência da Computação,32°
50,016958-7,Marco Antônio Kremer,L1,2,Ciência da Computação,233°
57,007680-5,Pietra Ferreira Renner,AC,2,Ciência da Computação,29°
58,011637-8,Rafael Fernandes Gutterres da Rocha,L4,2,Ciência da Computação,267°
67,006884-5,Vinicius Barreto da Luz,L1,2,Ciência da Computação,231°

In [ ]:
# Tirando o caractere "°"
dados['Classificação'].replace(to_replace="°", value="", inplace=True, regex = True)

# Transformando para inteiro
dados['Classificação'] = dados['Classificação'].astype(int)

# Ordenando a Classificação:
dados_ordenados = dados.sort_values(by = "Classificação").reset_index()

del dados_ordenados['index']

In [ ]:
dados_ordenados.head(5)

,Inscrição,Nome,Vaga obtida,Semestre,Curso,Classificação
0,009427-7,Fernando Kaspary Fink,AC,1,Ciência da Computação,1
1,007728-3,Beatriz Forneck Soviero,AC,1,Ciência da Computação,2
2,001781-7,Miguel Lemmertz Schwarzbold,AC,1,Ciência da Computação,3
3,020177-4,Henrique Soares Ribeiro Sant'Anna de Oliveira,AC,1,Ciência da Computação,4
4,002340-0,Gabriel Carvalho Ávila,AC,1,Ciência da Computação,5

In [ ]:
# primeiro semestre ordenado

primeiro_semestre = dados_ordenados.query('Semestre == 1').reset_index()
del primeiro_semestre['index']
primeiro_semestre

,Inscrição,Nome,Vaga obtida,Semestre,Curso,Classificação
0,009427-7,Fernando Kaspary Fink,AC,1,Ciência da Computação,1
1,007728-3,Beatriz Forneck Soviero,AC,1,Ciência da Computação,2
2,001781-7,Miguel Lemmertz Schwarzbold,AC,1,Ciência da Computação,3
3,020177-4,Henrique Soares Ribeiro Sant'Anna de Oliveira,AC,1,Ciência da Computação,4
4,002340-0,Gabriel Carvalho Ávila,AC,1,Ciência da Computação,5
5,013127-0,Eduarda Tessari Pereira,AC,1,Ciência da Computação,6
6,004947-6,Guilherme Ismael Flach,AC,1,Ciência da Computação,7
7,001309-9,Mateus da Luz Matos Cezar,AC,1,Ciência da Computação,8
8,008704-1,Diego Hommerding Amorim,AC,1,Ciência da Computação,9
9,004610-8,Vinícius Daniel Spadotto,AC,1,Ciência da Computação,10
10,016961-7,Walter Frank,AC,1,Ciência da Computação,11
11,019806-4,Nathan Hoffmann Passuello,AC,1,Ciência da Computação,12
12,008828-5,Marcelo Gross Borges,AC,1,Ciência da Computação,13
13,012921-6,Leonardo Gonzatti Heisler,AC,1,Ciência da Computação,14
14,013662-0,Gabriel Kenji Yatsuda Ikuta,AC,1,Ciência da Computação,15
15,000284-4,Afonso Hafner de Britto,AC,1,Ciência da Computação,16
16,006747-4,Gustavo Zen Pretto,AC,1,Ciência da Computação,17
17,008365-8,Leonardo Silva Faria,AC,1,Ciência da Computação,18
18,012197-5,Tiago Vieira Dillenburg,AC,1,Ciência da Computação,19
19,012813-9,Sandro Rudiero Saibro Viégas,AC,1,Ciência da Computação,20
20,007276-1,Bruno Fialho Zawacki,AC,1,Ciência da Computação,21
21,010998-3,Gustavo Bender,AC,1,Ciência da Computação,22
22,009835-3,Gabriel Carvalho Tavares,AC,1,Ciência da Computação,23
23,015798-8,Lucas Campos Machado,AC,1,Ciência da Computação,24
24,005274-4,Gabriel Fernando Giaretta,AC,1,Ciência da Computação,25
25,007326-1,Thiago Frazzon Arend,AC,1,Ciência da Computação,26
26,012311-0,Raquel da Silva Ramos,AC,1,Ciência da Computação,27
27,006748-2,Roger Nathan Gonçalves Schmidt,L3,1,Ciência da Computação,37
28,012049-9,Thomas Schneider Wiederkehr,L3,1,Ciência da Computação,38
29,007214-1,Laís Fernanda Canabarro Araujo,L3,1,Ciência da Computação,40
30,008316-0,Tális Breda,L1,1,Ciência da Computação,55
31,009299-1,Laura Reis da Silveira,L4,1,Ciência da Computação,78
32,018514-0,Guilherme Poletti da Costa,L1,1,Ciência da Computação,95
33,009420-0,João Pedro Klippel Brusch,L13,1,Ciência da Computação,104
34,019887-0,João Pedro Giordani de Souza,L14,1,Ciência da Computação,137
35,003968-3,Gabriel Zurawski de Souza,L2,1,Ciência da Computação,143
36,002723-5,Marcos da Silva Bagatini,L1,1,Ciência da Computação,148
37,011751-0,Beatriz Aline Arend,L1,1,Ciência da Computação,155
38,019778-5,Luan Figueredo Dias,L13,1,Ciência da Computação,179
39,012164-9,Kamille Konarzewski Pimentel,L1,1,Ciência da Computação,184
40,017922-1,Emilson Livramento Silva,L4,1,Ciência da Computação,185
41,013385-0,Gabriel Arusiewicz Berta,L1,1,Ciência da Computação,194
42,011419-7,Jorge Antônio Noll dos Santos,L1,1,Ciência da Computação,206
43,009128-6,Samuel Sodré da Rosa,L1,1,Ciência da Computação,208
44,004595-0,Eduardo Godois Saldanha,L1,1,Ciência da Computação,210
45,002139-3,Maria Eduarda Santos Oliveira,L1,1,Ciência da Computação,215
46,008030-6,João Vitor Vogel,L1,1,Ciência da Computação,217
47,011109-0,Bruno Martins Alexandre,L13,1,Ciência da Computação,220
48,000898-2,Eduarda da Silva Alves,L4,1,Ciência da Computação,224
49,018546-9,Gabriel dos Reis Vargas,L4,1,Ciência da Computação,244
50,006242-1,Pedro Henrique Gomes Lourenço,L4,1,Ciência da Computação,253
51,003368-5,Julianne Emanuelle Martins Carrazzoni,L2,1,Ciência da Computação,258
52,018226-5,Maicon Figueiró da Silva,L2,1,Ciência da Computação,266

In [ ]:
# segundo semestre ordenado

segundo_semestre = dados_ordenados.query('Semestre == 2').reset_index()
del segundo_semestre['index']
segundo_semestre

,Inscrição,Nome,Vaga obtida,Semestre,Curso,Classificação
0,020160-0,Cristopher dos Santos Filho,AC,2,Ciência da Computação,28
1,007680-5,Pietra Ferreira Renner,AC,2,Ciência da Computação,29
2,012905-4,João Gabriel Rau Wendt,AC,2,Ciência da Computação,30
3,007385-7,Anísio Neto Meneses Lorentz,AC,2,Ciência da Computação,31
4,001395-1,Luca Mello Piccoli,AC,2,Ciência da Computação,32
5,004248-0,Gabriel Alves Barbosa,AC,2,Ciência da Computação,33
6,007272-9,João Gabriel Eberhardt Pereira,AC,2,Ciência da Computação,34
7,014265-4,Felipe Thaddeu Gassen,AC,2,Ciência da Computação,35
8,014936-5,Artur Coletti Valente,L3,2,Ciência da Computação,44
9,010155-9,Andressa Della Torre Salgado,L1,2,Ciência da Computação,228
10,006884-5,Vinicius Barreto da Luz,L1,2,Ciência da Computação,231
11,016958-7,Marco Antônio Kremer,L1,2,Ciência da Computação,233
12,011023-0,Felipe Avencourt Soares,L13,2,Ciência da Computação,255
13,005805-0,Gustavo da Encarnação Rodrigues,L4,2,Ciência da Computação,259
14,019600-2,Isasc Ventura de Oliveira,L4,2,Ciência da Computação,261
15,011637-8,Rafael Fernandes Gutterres da Rocha,L4,2,Ciência da Computação,267
16,003987-0,Alice Farias Gomes,L2,2,Ciência da Computação,274

# Transformando para um arquivo .csv

In [ ]:
# O dataframe do curso de Ciência da Computação em ordem de classificação:
dados_ordenados.to_csv('listao_ufrgs_cc.csv', index = False)

# O dataframe do listao em ordem alfabética:
novo_listao.to_csv('listao_ufrgs.csv', index = False)

In [ ]:
# Visualizando o .csv criado: 

pd.read_csv('listao_ufrgs_cc.csv')

,Inscrição,Nome,Vaga obtida,Semestre,Curso,Classificação
0,009427-7,Fernando Kaspary Fink,AC,1,Ciência da Computação,1
1,007728-3,Beatriz Forneck Soviero,AC,1,Ciência da Computação,2
2,001781-7,Miguel Lemmertz Schwarzbold,AC,1,Ciência da Computação,3
3,020177-4,Henrique Soares Ribeiro Sant'Anna de Oliveira,AC,1,Ciência da Computação,4
4,002340-0,Gabriel Carvalho Ávila,AC,1,Ciência da Computação,5
...,...,...,...,...,...,...
65,005805-0,Gustavo da Encarnação Rodrigues,L4,2,Ciência da Computação,259
66,019600-2,Isasc Ventura de Oliveira,L4,2,Ciência da Computação,261
67,018226-5,Maicon Figueiró da Silva,L2,1,Ciência da Computação,266
68,011637-8,Rafael Fernandes Gutterres da Rocha,L4,2,Ciência da Computação,267
69,003987-0,Alice Farias Gomes,L2,2,Ciência da Computação,274

In [ ]:
pd.read_csv('listao_ufrgs.csv')

,Inscrição,Nome,Vaga obtida,Semestre,Curso,Classificação
0,012590-3,Abyner da Silva Vargas,AC,2,Engenharia Elétrica,34°
1,010853-7,Acácia Rufatto,AC,1,Letras - Licenciatura,8°
2,008034-9,Adriana Cecchin Fajreldines,AC,2,Engenharia Hídrica,2°
3,017920-5,Adriana de Freitas Rodrigues,L4,1,Filosofia - Bacharelado Diurno,25°
4,016305-8,Adriane Inês Backes Sehn,AC,1,Geografia - Diurno,2°
...,...,...,...,...,...,...
3113,006621-4,Yuri Daniel Hahn da Silva,AC,1,Ciências Econômicas - Diurno,14°
3114,011230-5,Yuri Henrique Bittencourt Correa,AC,1,Ciências Atuariais - Noturno,11°
3115,000642-4,Yuri Magalhães Franklin de Oliveira,L2,1,Engenharia de Computação,121°
3116,013605-0,Yuri Pereira,AC,1,Políticas Públicas - Noturno,4°
3117,008678-9,Zara Mattos de Magalhães,L1,1,Relações Públicas,30°